---
title: "R Notebook"
output: html_notebook
---
According to the Swiss Federal Statistical Office, the population of Switzerland has grown from 7,955 millions in 2011 to 8,670 millions in 2020. This number continues to grow as well as the number of foreign citizens living in Switzerland. At some point, some of those foreigners acquire the Swiss citizenship and integrate the Swiss society. In this report we explore the dataset containing information about the people who as foreign nationals obtained a Swiss passport.
The aim of this report is to analyze how the naturalization in Switzerland evolved in the last years and to understand the profile of the people that seek to obtain a Swiss nationality. Since, there is many attributes that we should take into account, we thoroughly analyze the characteristics of such people, as well as the way they obtained the Swiss nationality.

The following analysis is performed using the data that is provided by the Swiss Federal Statistical Office (referred as FSO later in the report), which is the national competence center for official statistics in Switzerland. The analysis is performed on the data generated between 2011 and 2020.

We are particularly interested in this interval of time because in June 2014, the Swiss Parliament updated the Federal Act on Swiss Citizenship (RS 141.0) and passed a law that restricts heavily the process of naturalization and adds new conditions to it. The law entered in force in January 2018. One of the motivation of this report is to verify and inspect the effects of this law on the number of naturalizations.

For this report, we are using 2 complementary datasets: the annual population of Switzerland by cantons and the geographical characteristics of the cantons. Both of the datasets are provided by the FSO. The main dataset that is used for the report is composed of the following variables:





First, to form an idea about our research question, let's have a look on how the number of naturalizations is distributed accross Switzerland. The easisest way to do that in terms of visualization, is to plot our data as a geographic map of Switzerland and draw borders between cantons. The map represents the total number of people who acquired a Swiss citizenship between 2011 and 2020 within each canton. The magnitude is represented by the darkness of the blue color: the darker the filling of the canton is - the more people obtained a Swiss passport in that canton. Over hte 9 years, the cantons with the highest numbers of naturalizations are: Zurich, Vaud and Geneva. These findings make sense as each of these 3 cantons contain big cities in terms of population: Zurich, Lausanne and Geneva. These cities, in fact, hold a big concentration of foreign citizens since many international organizations, headquarters of multinational companies and universities are based in them.

We can visualize the same map as a gif which changes the filling of cantons depending on the year. We notice that through years, cantons of Switzerland with the most naturalizations are Zurich, Geneva and Vaud. We also notice that through years, the difference in numbers between cantons tends to change. 



To inspect the difference of numbers of naturalizations through time, we propose to plot a time series plot which represents the total number of naturalizations in Switzerland between 2011 and 2020. Before 2014, the number of naturalizations tend to be more or less constant (34'102 on average naturalizations each year). From 2014 to 2017, the number of new citizens increased every year until it reached 44'949 in 2017. After, 2017 the number of naturalizations decreased until 34'141 in 2020 (close to the numbers of naturalizations before the increase in 2014).


In the plot, the black dots represent the number of naturalizations for each of the 26 cantons by year. The blue smooth line represents the conditional mean of the number of naturalizations given the year. We notice that an important share of the points is situated below 3000 and every year has 2 - 4 outliers. Over the years, the conditional mean seems to slightly increase until 2017 and decrease after.


We explore in this plot the distribution of number of naturalization for yeach year. It seems that the boxes doesn't change a lot over the years, but we notice that the number of outliers increases through time.




Comparing the cantons between themselves without accounting for their difference in populations may lead to wrong conclusions. Here, we plot the map of Switzerland and devide the total number of naturalizations in a canton by the population of the said canton. We then multiply this number by hundred. The obtained number for each canton represents the share of the new Swiss citizens for each canton. This manipulation allows us to see the relative difference the number of naturalisations between cantons to the population.
We notice that the cantons with the highest rates are still Geneva, Vaud and Zurich, but the order changes. Also, we notice that cantons of Valais and Ticino have also high rates. Overall, we notice that the difference, in terms of magnitude, seems to be much lower than before (when we didn't account for the population.)


The gif represening the change by years of the naturalization's rate for each canton, shows that the difference in rates seems to change over year and to be higher from 2015 to 2017 compared to other years.



We can inspect the change through time of the the number of naturalizations by canton by a stacked time series plot where each leayer represents a canton. As mentioned previously, the highest numbers of naturalizations tend to have cantons of Zurich, Vaud and Geneva. We notice as well, that all cantons seem to follow a similar pattern, constant before 2014, increase until 2017 and decrease after. We also notice that cantons of Vaud and Geneva had a stronger increase in 2014 than other cantons. Between 2014 and 2016 the number of naturalizations more than trippled in Geneva,in Vaud almost doubled.




By inspecting the relative number over time for each canton, we notice again that the cantons follow a similar pattern But as the population increases, the number of naturalizations increases and the difference in years seems to be smaller in relative numbers. However, we still notice that the share of Geneva and Vaud seems to increase a lot after 2014. 




The plot explores the composition of the total number of naturalizations between 2011 and 2020 by gender and the age group. Within each group, we visualize the type of the naturalization that was performed. We notice that the age groups which tend to have the highest numbers of naturalizations belong to the groups of 10-19, 30-39 and 40-49. We may assume, that these age categories correspond to working professionals and their children. Also, we notice that for age groups of 30-39 and 40-49 the shares od ordinary and simplified naturalizations are very close, for other gorups, the ordinary naturalization seems to be much more higher. Also, the simplified naturalization tend to be slighlkt higher for females belonging to the age groups 30-39 and 40-49 than males of the same age groups. Another interesting finding, is that the 3 least popular types of naturalizations: specifically, naturalization by adoption, naturalization by confirmation of the Swiss nationality and Reintegration, are inexistant for most of the age groups. Naturalization by adoption and naturalization by confirmation of the Swiss nationality arepresent for age groups of 0-9 and 10-19. The share of naturalization by integration seems to be very small for all the age groups.


THe gif represents the change of the composition over the years of the number of naturalizations by gender and the age groups. We notice, as stated previously, that there seems to been overall increase before 2017 followed by a deacrease. The composition seems to stay similar over the years,but minor changes happen within the groups. The rest of the report concentrates more thoroughly on each group depeng onthe type of naturalization.






